# ----------------------------------
#          INSTALL & TEST
# ----------------------------------
install_requirements:
	@pip install -r requirements.txt

run_streamlit:
	streamlit run streamlit/app.py
